= Closing Words

////
Video segments: closing-words.mp4
extracted from
https://drive.google.com/file/d/1x8WS_DQjKyOW_o3T7_WM9xXAe4rLgMWt/view?usp=sharing

45:45::
End of demo. Closing words.
////

This section explores possibilities for expanding the PoC environment created by this course.

_Watch the optional video and then read the closing section._

WARNING: If you have issues watching the video embedded in this page, watch it directly on the https://videos.learning.redhat.com/media/hcp-on-bm-intro/1_4eihw75o[Red Hat media space^], which requires the Red Hat VPN and an employee log in.

++++
<iframe type="text/javascript" src='https://cdnapisec.kaltura.com/p/2032581/embedPlaykitJs/uiconf_id/49478072?iframeembed=true&entry_id=1_1f8ltycl' style="width: 768px; height: 432px" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" frameborder="0"></iframe>
++++

//Red Hat media space and ROL use different instances of Kaltura. The iframe uses the ROL instance.

We hope you find this content useful and it enables you to learn about and demonstrate OpenShift Hosted Control Planes.

You can use the environment described here, and expand on the provided Ansible playbooks, to try more sophisticated scenarios. If you do so, please offer pull requests to the original Git repository at https://github.com/v2pkthakur/hcp-on-bm.